//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 4.4.5.39286;
// 		Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;
using System.Data.SQLite;
using System.IO;
using System.Reflection;
using System.Web;

using TextMetal.Core;
using TextMetal.Core.Plumbing;

namespace TextMetal.WebHostSample.Objects.Model
{
	public partial class DatabaseFileManager
	{
		#region Constructors/Destructors

		public DatabaseFileManager(string underlyingDatabaseFilePath)
		{
			if ((object)underlyingDatabaseFilePath == null)
				throw new ArgumentNullException("underlyingDatabaseFilePath");

			if (DataType.IsWhiteSpace(underlyingDatabaseFilePath))
				throw new ArgumentOutOfRangeException("underlyingDatabaseFilePath");

			this.underlyingDatabaseFilePath = underlyingDatabaseFilePath;
		}

		#endregion

		#region Fields/Constants

		private readonly string underlyingDatabaseFilePath;

		#endregion

		#region Properties/Indexers/Events

		public static string DatabaseDirectoryPath
		{
			get
			{
				return AppConfig.GetAppSetting<string>("TextMetal.WebHostSample.Objects.Model::DatabaseDirectoryPath");
			}
		}

		public static string DatabaseFileName
		{
			get
			{
				return AppConfig.GetAppSetting<string>("TextMetal.WebHostSample.Objects.Model::DatabaseFileName");
			}
		}

		public static string DatabaseFilePath
		{
			get
			{
				string value;

				// {0} == GetApplicationUserSpecificDirectoryPath()
				value = Path.Combine(string.Format(DatabaseDirectoryPath ?? "", GetApplicationUserSpecificDirectoryPath()), DatabaseFileName);

				return value;
			}
		}

		public static bool KillDatabaseFile
		{
			get
			{
				bool value;

				if (!AppConfig.HasAppSetting("TextMetal.WebHostSample.Objects.Model::KillDatabaseFile"))
					return false;

				value = AppConfig.GetAppSetting<bool>("TextMetal.WebHostSample.Objects.Model::KillDatabaseFile");

				return value;
			}
		}

		public static bool UseDatabaseFile
		{
			get
			{
				bool value;

				value = AppConfig.GetAppSetting<bool>("TextMetal.WebHostSample.Objects.Model::UseDatabaseFile");

				return value;
			}
		}

		public string UnderlyingDatabaseFilePath
		{
			get
			{
				return this.underlyingDatabaseFilePath;
			}
		}

		#endregion

		#region Methods/Operators
		
		static partial void OnCreateDatabaseFileForNative(string databaseFilePath, ref bool result)
		{
			if (!UseDatabaseFile)
				return;

			SQLiteConnection.CreateFile(databaseFilePath);
		}
		
		private static string GetApplicationUserSpecificDirectoryPath()
		{
			Assembly assembly;
			AssemblyInformation assemblyInformation;
			string userSpecificDirectoryPath;
			
			if (ExecutionPathStorage.IsInHttpContext)
				userSpecificDirectoryPath = Path.GetFullPath(HttpContext.Current.Server.MapPath("~/"));
			else
			{
				assembly = Assembly.GetExecutingAssembly();
				assemblyInformation = new AssemblyInformation(assembly);
				
				if ((object)assemblyInformation.Company != null &&
					(object)assemblyInformation.Product != null &&
					(object)assemblyInformation.Win32FileVersion != null)
				{
					userSpecificDirectoryPath = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
					userSpecificDirectoryPath = Path.Combine(userSpecificDirectoryPath, assemblyInformation.Company);
					userSpecificDirectoryPath = Path.Combine(userSpecificDirectoryPath, assemblyInformation.Product);
					userSpecificDirectoryPath = Path.Combine(userSpecificDirectoryPath, assemblyInformation.Win32FileVersion);
				}
				else
					userSpecificDirectoryPath = Path.GetFullPath(".");
			}
			
			return userSpecificDirectoryPath;
		}

		/*private static string GetConnectionString(string databaseFilePath)
		{
			if ((object)databaseFilePath == null)
				throw new ArgumentNullException("databaseFilePath");

			if (DataType.IsNullOrWhiteSpace(databaseFilePath))
				throw new ArgumentOutOfRangeException("databaseFilePath");

			return string.Format("Data Source={0}", databaseFilePath);
		}*/

		public static void InitDatabase(Type type, string resource)
		{
			DatabaseHistory history;
			DatabaseFileManager databaseFileManager;

			if ((object)type == null)
				throw new ArgumentNullException("type");

			if ((object)resource == null)
				throw new ArgumentNullException("resource");

			if (DataType.IsNullOrWhiteSpace(resource))
				throw new ArgumentOutOfRangeException("resource");

			if (UseDatabaseFile)
			{
				if (!DataType.IsNullOrWhiteSpace(DatabaseFilePath))
				{
					if (KillDatabaseFile)
					{
						if (File.Exists(DatabaseFilePath))
							File.Delete(DatabaseFilePath);
					}
					
					databaseFileManager = new DatabaseFileManager(DatabaseFilePath);
					databaseFileManager.EnsureDatabaseFile();
				}

				if (!Cerealization.TryGetFromAssemblyResource<DatabaseHistory>(type, resource, out history))
					throw new InvalidOperationException(string.Format("Unable to deserialize instance of '{0}' from the manifest resource name '{1}' in the assembly '{2}'.", typeof(DatabaseHistory).FullName, resource, type.Assembly.FullName));

				using (UnitOfWorkContext unitOfWorkContext = Repository.GetUnitOfWorkContext())
				{
					history.PerformSchemaUpgrade(unitOfWorkContext);

					unitOfWorkContext.Complete();
				}
			}
		}

		private bool EnsureDatabaseFile()
		{
			string databaseFilePath;
			string databaseDirectoryPath;
			bool retval = false;

			databaseFilePath = Path.GetFullPath(this.UnderlyingDatabaseFilePath);
			databaseDirectoryPath = Path.GetDirectoryName(databaseFilePath);

			if (!Directory.Exists(databaseDirectoryPath))
				Directory.CreateDirectory(databaseDirectoryPath);

			if (!File.Exists(databaseFilePath))
			{
				OnCreateDatabaseFileForNative(databaseFilePath, ref retval);
			}

			return retval;
		}
		
		static partial void OnCreateDatabaseFileForNative(string databaseFilePath, ref bool result);

		#endregion
	}
}
