//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 4.4.5.39286;
// 		Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;

using TextMetal.Core.Plumbing;

using Facet = TextMetal.Core.ExpressionModel.SurfaceConstruct;

namespace TextMetal.WebHostSample.Objects.Model
{
	public sealed class Order
	{		
		#region Constructors/Destructors
		
		public Order(Facet facet, bool ascending)
		{
			if ((object)facet == null)
				throw new ArgumentNullException("facet");

			this.facet = facet;
			this.ascending = ascending;
		}
		
		#endregion
		
		#region Fields/Constants

		private bool ascending;
		private Facet facet;

		#endregion

		#region Properties/Indexers/Events

		public bool Ascending
		{
			get
			{
				return this.ascending;
			}
		}

		public Facet Facet
		{
			get
			{
				return this.facet;
			}
		}

		#endregion
	}
}
