//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 4.4.5.39286;
// 		Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;
using System.Collections.Generic;
using System.Data;

using TextMetal.Core.Plumbing;

namespace TextMetal.WebHostSample.Objects.Model
{
	public partial class Repository : IRepository
	{		
		#region Constructors/Destructors
		
		public Repository()
		{
		}
		
		#endregion
		
		#region Fields/Constants
		
		private const string CONNECTION_STRING_NAME = "TextMetal.WebHostSample.Objects.Model::ConnectionString";
						
		#endregion
		
		#region Properties/Indexers/Events
		
		public static string ConnectionString
		{
			get
			{
				string connectionString;

				connectionString = AppConfig.GetConnectionString(CONNECTION_STRING_NAME);

				OnPreProcessConnectionString(ref connectionString);
				
				return connectionString;
			}
		}
		
		public static Type ConnectionType
		{
			get
			{
				return Type.GetType(AppConfig.GetConnectionProvider(CONNECTION_STRING_NAME), true);
			}
		}
				
		#endregion
		
		#region Methods/Operators
		
		static partial void OnPreProcessConnectionString(ref string connectionString)
		{
			if (!DatabaseFileManager.UseDatabaseFile)
				return;

			// {0} = DatabaseFileManager.DatabaseFilePath
			connectionString = string.Format(connectionString ?? "", DatabaseFileManager.DatabaseFilePath);
		}


#if DEBUG
		static partial void OnProfileCommand(Type modelType, CommandType commandType, string commandText, IList<IDataParameter> commandParameters, bool executeAsCud, int thisOrThatRecordsAffected)
		{
			/* THIS METHOD SHOULD NOT BE DEFINED IN RELEASE/PRODUCTION BUILDS */
			
			// these are by convention in the TextMetal.Core.Plumbing.AdoNetHelper.ExecuteDictionary(...) API.
			const bool COMMAND_PREPARE = false;
			/* const */ int? COMMAND_TIMEOUT = null;
			const CommandBehavior COMMAND_BEHAVIOR = CommandBehavior.Default;

			string value = "";
			int i;

			value += "\r\n[+++ begin trace +++]\r\n";

			value += string.Format("[Command]: Type = '{0}'; Text = '{1}'; Prepare = '{2}'; Timeout = '{3}'; Behavior = '{4}'.",
								   commandType, commandText, COMMAND_PREPARE, COMMAND_TIMEOUT, COMMAND_BEHAVIOR);

			i = 0;
			foreach (IDbDataParameter commandParameter in commandParameters)
			{
				value += string.Format("\r\n\t[Parameter{0:00}]: Direction = '{1}'; ParameterName = '{2}'; IsNullable = '{3}'; Precision = '{4}'; Scale = '{5}'; Size = '{6}'; DbType = '{7}'; Value = '{8}'.",
									   i++, commandParameter.Direction, commandParameter.ParameterName, commandParameter.IsNullable, commandParameter.Precision, commandParameter.Scale, commandParameter.Size, commandParameter.DbType, (object)commandParameter != null ? commandParameter.Value : "<<null>>");
			}

			value += "\r\n[+++ end trace +++]\r\n";

			System.Diagnostics.Trace.WriteLine(value);
		}
#endif		
		
		public static UnitOfWorkContext GetUnitOfWorkContext()
		{
			return UnitOfWorkContext.Create(ConnectionType, ConnectionString, true);
		}
		
		public static void InitDatabase()
		{
			string resourceName;
			const string CONNECTION_SPECIFIC_RESOURCE_NAME = "TextMetal.WebHostSample.Objects.Model.SQL.RevisionHistory({0}).xml";
			
			switch (ConnectionType.Name.ToLower())
			{
				case "sqlconnection":
				case "sqliteconnection":
					resourceName = string.Format(CONNECTION_SPECIFIC_RESOURCE_NAME, ConnectionType.Name);
					break;
				default:
					throw new InvalidOperationException("TODO (enhancement): add meaningful message"); 
			}

			DatabaseFileManager.InitDatabase(typeof(Repository), resourceName);
		}
		
		private static string ConnectionSpecificGetIdentityCommand()
		{
			switch (ConnectionType.Name.ToLower())
			{
				case "sqlconnection":
					return SqlServerSpecificGetIdentityCommand();
				case "sqliteconnection":
					return SqliteSpecificGetIdentityCommand();
				default:
					throw new InvalidOperationException("TODO (enhancement): add meaningful message");
			}
		}
		
		private static string ConnectionSpecificGetTableName(string schemaName, string tableName)
		{
			switch (ConnectionType.Name.ToLower())
			{
				case "sqlconnection":
					return SqlServerSpecificGetTableName(schemaName, tableName);
				case "sqliteconnection":
					return SqliteSpecificGetTableName(schemaName, tableName);
				default:
					throw new InvalidOperationException("TODO (enhancement): add meaningful message");
			}
		}

		private static string ConnectionSpecificGetTableAlias(string tableAlias)
		{
			switch (ConnectionType.Name.ToLower())
			{
				case "sqlconnection":
					return SqlServerSpecificGetTableAlias(tableAlias);
				case "sqliteconnection":
					return SqliteSpecificGetTableAlias(tableAlias);
				default:
					throw new InvalidOperationException("TODO (enhancement): add meaningful message");
			}
		}

		internal static string ConnectionSpecificGetParameterName(string parameterName)
		{
			switch (ConnectionType.Name.ToLower())
			{
				case "sqlconnection":
					return SqlServerSpecificGetParameterName(parameterName);
				case "sqliteconnection":
					return SqliteSpecificGetParameterName(parameterName);
				default:
					throw new InvalidOperationException("TODO (enhancement): add meaningful message");
			}
		}

		private static string ConnectionSpecificGetColumnName(string columnName)
		{
			switch (ConnectionType.Name.ToLower())
			{
				case "sqlconnection":
					return SqlServerSpecificGetColumnName(columnName);
				case "sqliteconnection":
					return SqliteSpecificGetColumnName(columnName);
				default:
					throw new InvalidOperationException("TODO (enhancement): add meaningful message");
			}
		}

		internal static string ConnectionSpecificGetAliasedColumnName(string tableAlias, string columnName)
		{
			switch (ConnectionType.Name.ToLower())
			{
				case "sqlconnection":
					return SqlServerSpecificGetAliasedColumnName(tableAlias, columnName);
				case "sqliteconnection":
					return SqliteSpecificGetAliasedColumnName(tableAlias, columnName);
				default:
					throw new InvalidOperationException("TODO (enhancement): add meaningful message");
			}
		}

		private static void ConnectionSpecificParameterMagic(UnitOfWorkContext unitOfWorkContext, IDataParameter commandParameter, string generatedFromColumnNativeType)
		{
			if ((object)unitOfWorkContext == null)
				throw new ArgumentNullException("unitOfWorkContext");

			if ((object)commandParameter == null)
				throw new ArgumentNullException("commandParameter");

			switch (ConnectionType.Name.ToLower())
			{
				case "sqlconnection":
					SqlServerSpecificParameterMagic(unitOfWorkContext, commandParameter, generatedFromColumnNativeType);
					break;
				case "sqliteconnection":
					SqliteSpecificParameterMagic(unitOfWorkContext, commandParameter, generatedFromColumnNativeType);
					break;
				default:
					throw new InvalidOperationException("TODO (enhancement): add meaningful message");
			}
		}

		private static void ConnectionSpecificCommandMagic(UnitOfWorkContext unitOfWorkContext, bool executeAsCud, out int thisOrThatRecordsAffected)
		{
			if ((object)unitOfWorkContext == null)
				throw new ArgumentNullException("unitOfWorkContext");
			
			if (executeAsCud)
			{
				switch (ConnectionType.Name.ToLower())
				{
					case "sqlconnection":
						thisOrThatRecordsAffected = SQL_SERVER_PERSIST_NOT_EXPECTED_RECORDS_AFFECTED;
						break;
					case "sqliteconnection":
						thisOrThatRecordsAffected = SQLITE_PERSIST_NOT_EXPECTED_RECORDS_AFFECTED;
						break;
					default:
						throw new InvalidOperationException("TODO (enhancement): add meaningful message"); 
				}
			}
			else
			{
				switch (ConnectionType.Name.ToLower())
				{
					case "sqlconnection":
						thisOrThatRecordsAffected = SQL_SERVER_QUERY_EXPECTED_RECORDS_AFFECTED;
						break;
					case "sqliteconnection":
						thisOrThatRecordsAffected = SQLITE_QUERY_EXPECTED_RECORDS_AFFECTED;
						break;
					default:
						throw new InvalidOperationException("TODO (enhancement): add meaningful message"); 
				}
			}
		}
		
		static partial void OnProfileCommand(Type modelType, CommandType commandType, string commandText, IList<IDataParameter> commandParameters, bool executeAsCud, int thisOrThatRecordsAffected);
		
		static partial void OnPreProcessConnectionString(ref string connectionString);
		
		protected delegate TResult Stank<T1, TResult>(T1 p1);

		protected delegate TResult Stank<T1, T2, TResult>(T1 p1, T2 p2);

		protected delegate TResult Stank<T1, T2, T3, TResult>(T1 p1, T2 p2, T3 p3);

		protected delegate TResult Stank<T1, T2, T3, T4, TResult>(T1 p1, T2 p2, T3 p3, T4 p4);

		protected delegate TResult Stank<T1, T2, T3, T4, T5, TResult>(T1 p1, T2 p2, T3 p3, T4 p4, T5 p5);

		protected delegate TResult Stank<T1, T2, T3, T4, T5, T6, TResult>(T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6);

		protected delegate TResult Stank<T1, T2, T3, T4, T5, T6, T7, TResult>(T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7);

		protected delegate TResult Stank<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8);

		protected delegate TResult Stank<T1, T2, T3, T4, T5, T6, T7, T8, T9, TResult>(T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9);

		protected delegate TResult Stank<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TResult>(T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9, T10 p10);

		protected delegate TResult Stank<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TResult>(T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9, T10 p10, T11 p11);

		protected delegate TResult Stank<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TResult>(T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9, T10 p10, T11 p11, T12 p12);

		protected delegate TResult Stank<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TResult>(T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9, T10 p10, T11 p11, T12 p12, T13 p13);

		protected delegate TResult Stank<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TResult>(T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9, T10 p10, T11 p11, T12 p12, T13 p13, T14 p14);

		protected delegate TResult Stank<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TResult>(T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9, T10 p10, T11 p11, T12 p12, T13 p13, T14 p14, T15 p15);

		protected delegate TResult Stank<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TResult>(T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9, T10 p10, T11 p11, T12 p12, T13 p13, T14 p14, T15 p15, T16 p16);

		protected TResult ExecuteAmbientUnitOfWorkAware<T1, TResult>(Stank<UnitOfWorkContext, T1, TResult> callbackMethod, T1 p1)
		{			
			TResult retval;
			
			if ((object)UnitOfWorkContext.Current == null)
			{
				using (UnitOfWorkContext unitOfWorkContext = Repository.GetUnitOfWorkContext())
				{
					retval = callbackMethod(unitOfWorkContext, p1);
											
					unitOfWorkContext.Complete();
					
					return retval;
				}
			}			
			else
			{
				return callbackMethod(UnitOfWorkContext.Current, p1);
			}
		}

		protected TResult ExecuteAmbientUnitOfWorkAware<T1, T2, TResult>(Stank<UnitOfWorkContext, T1, T2, TResult> callbackMethod, T1 p1, T2 p2)
		{			
			TResult retval;
			
			if ((object)UnitOfWorkContext.Current == null)
			{
				using (UnitOfWorkContext unitOfWorkContext = Repository.GetUnitOfWorkContext())
				{
					retval = callbackMethod(unitOfWorkContext, p1, p2);
											
					unitOfWorkContext.Complete();
					
					return retval;
				}
			}			
			else
			{
				return callbackMethod(UnitOfWorkContext.Current, p1, p2);
			}
		}

		protected TResult ExecuteAmbientUnitOfWorkAware<T1, T2, T3, TResult>(Stank<UnitOfWorkContext, T1, T2, T3, TResult> callbackMethod, T1 p1, T2 p2, T3 p3)
		{			
			TResult retval;
			
			if ((object)UnitOfWorkContext.Current == null)
			{
				using (UnitOfWorkContext unitOfWorkContext = Repository.GetUnitOfWorkContext())
				{
					retval = callbackMethod(unitOfWorkContext, p1, p2, p3);
											
					unitOfWorkContext.Complete();
					
					return retval;
				}
			}			
			else
			{
				return callbackMethod(UnitOfWorkContext.Current, p1, p2, p3);
			}
		}

		protected TResult ExecuteAmbientUnitOfWorkAware<T1, T2, T3, T4, TResult>(Stank<UnitOfWorkContext, T1, T2, T3, T4, TResult> callbackMethod, T1 p1, T2 p2, T3 p3, T4 p4)
		{			
			TResult retval;
			
			if ((object)UnitOfWorkContext.Current == null)
			{
				using (UnitOfWorkContext unitOfWorkContext = Repository.GetUnitOfWorkContext())
				{
					retval = callbackMethod(unitOfWorkContext, p1, p2, p3, p4);
											
					unitOfWorkContext.Complete();
					
					return retval;
				}
			}			
			else
			{
				return callbackMethod(UnitOfWorkContext.Current, p1, p2, p3, p4);
			}
		}

		protected TResult ExecuteAmbientUnitOfWorkAware<T1, T2, T3, T4, T5, TResult>(Stank<UnitOfWorkContext, T1, T2, T3, T4, T5, TResult> callbackMethod, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5)
		{			
			TResult retval;
			
			if ((object)UnitOfWorkContext.Current == null)
			{
				using (UnitOfWorkContext unitOfWorkContext = Repository.GetUnitOfWorkContext())
				{
					retval = callbackMethod(unitOfWorkContext, p1, p2, p3, p4, p5);
											
					unitOfWorkContext.Complete();
					
					return retval;
				}
			}			
			else
			{
				return callbackMethod(UnitOfWorkContext.Current, p1, p2, p3, p4, p5);
			}
		}

		protected TResult ExecuteAmbientUnitOfWorkAware<T1, T2, T3, T4, T5, T6, TResult>(Stank<UnitOfWorkContext, T1, T2, T3, T4, T5, T6, TResult> callbackMethod, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6)
		{			
			TResult retval;
			
			if ((object)UnitOfWorkContext.Current == null)
			{
				using (UnitOfWorkContext unitOfWorkContext = Repository.GetUnitOfWorkContext())
				{
					retval = callbackMethod(unitOfWorkContext, p1, p2, p3, p4, p5, p6);
											
					unitOfWorkContext.Complete();
					
					return retval;
				}
			}			
			else
			{
				return callbackMethod(UnitOfWorkContext.Current, p1, p2, p3, p4, p5, p6);
			}
		}

		protected TResult ExecuteAmbientUnitOfWorkAware<T1, T2, T3, T4, T5, T6, T7, TResult>(Stank<UnitOfWorkContext, T1, T2, T3, T4, T5, T6, T7, TResult> callbackMethod, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7)
		{			
			TResult retval;
			
			if ((object)UnitOfWorkContext.Current == null)
			{
				using (UnitOfWorkContext unitOfWorkContext = Repository.GetUnitOfWorkContext())
				{
					retval = callbackMethod(unitOfWorkContext, p1, p2, p3, p4, p5, p6, p7);
											
					unitOfWorkContext.Complete();
					
					return retval;
				}
			}			
			else
			{
				return callbackMethod(UnitOfWorkContext.Current, p1, p2, p3, p4, p5, p6, p7);
			}
		}

		protected TResult ExecuteAmbientUnitOfWorkAware<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(Stank<UnitOfWorkContext, T1, T2, T3, T4, T5, T6, T7, T8, TResult> callbackMethod, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8)
		{			
			TResult retval;
			
			if ((object)UnitOfWorkContext.Current == null)
			{
				using (UnitOfWorkContext unitOfWorkContext = Repository.GetUnitOfWorkContext())
				{
					retval = callbackMethod(unitOfWorkContext, p1, p2, p3, p4, p5, p6, p7, p8);
											
					unitOfWorkContext.Complete();
					
					return retval;
				}
			}			
			else
			{
				return callbackMethod(UnitOfWorkContext.Current, p1, p2, p3, p4, p5, p6, p7, p8);
			}
		}

		protected TResult ExecuteAmbientUnitOfWorkAware<T1, T2, T3, T4, T5, T6, T7, T8, T9, TResult>(Stank<UnitOfWorkContext, T1, T2, T3, T4, T5, T6, T7, T8, T9, TResult> callbackMethod, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
		{			
			TResult retval;
			
			if ((object)UnitOfWorkContext.Current == null)
			{
				using (UnitOfWorkContext unitOfWorkContext = Repository.GetUnitOfWorkContext())
				{
					retval = callbackMethod(unitOfWorkContext, p1, p2, p3, p4, p5, p6, p7, p8, p9);
											
					unitOfWorkContext.Complete();
					
					return retval;
				}
			}			
			else
			{
				return callbackMethod(UnitOfWorkContext.Current, p1, p2, p3, p4, p5, p6, p7, p8, p9);
			}
		}

		protected TResult ExecuteAmbientUnitOfWorkAware<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TResult>(Stank<UnitOfWorkContext, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TResult> callbackMethod, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9, T10 p10)
		{			
			TResult retval;
			
			if ((object)UnitOfWorkContext.Current == null)
			{
				using (UnitOfWorkContext unitOfWorkContext = Repository.GetUnitOfWorkContext())
				{
					retval = callbackMethod(unitOfWorkContext, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10);
											
					unitOfWorkContext.Complete();
					
					return retval;
				}
			}			
			else
			{
				return callbackMethod(UnitOfWorkContext.Current, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10);
			}
		}

		protected TResult ExecuteAmbientUnitOfWorkAware<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TResult>(Stank<UnitOfWorkContext, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TResult> callbackMethod, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9, T10 p10, T11 p11)
		{			
			TResult retval;
			
			if ((object)UnitOfWorkContext.Current == null)
			{
				using (UnitOfWorkContext unitOfWorkContext = Repository.GetUnitOfWorkContext())
				{
					retval = callbackMethod(unitOfWorkContext, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11);
											
					unitOfWorkContext.Complete();
					
					return retval;
				}
			}			
			else
			{
				return callbackMethod(UnitOfWorkContext.Current, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11);
			}
		}

		protected TResult ExecuteAmbientUnitOfWorkAware<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TResult>(Stank<UnitOfWorkContext, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TResult> callbackMethod, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9, T10 p10, T11 p11, T12 p12)
		{			
			TResult retval;
			
			if ((object)UnitOfWorkContext.Current == null)
			{
				using (UnitOfWorkContext unitOfWorkContext = Repository.GetUnitOfWorkContext())
				{
					retval = callbackMethod(unitOfWorkContext, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12);
											
					unitOfWorkContext.Complete();
					
					return retval;
				}
			}			
			else
			{
				return callbackMethod(UnitOfWorkContext.Current, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12);
			}
		}

		protected TResult ExecuteAmbientUnitOfWorkAware<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TResult>(Stank<UnitOfWorkContext, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TResult> callbackMethod, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9, T10 p10, T11 p11, T12 p12, T13 p13)
		{			
			TResult retval;
			
			if ((object)UnitOfWorkContext.Current == null)
			{
				using (UnitOfWorkContext unitOfWorkContext = Repository.GetUnitOfWorkContext())
				{
					retval = callbackMethod(unitOfWorkContext, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13);
											
					unitOfWorkContext.Complete();
					
					return retval;
				}
			}			
			else
			{
				return callbackMethod(UnitOfWorkContext.Current, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13);
			}
		}

		protected TResult ExecuteAmbientUnitOfWorkAware<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TResult>(Stank<UnitOfWorkContext, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TResult> callbackMethod, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9, T10 p10, T11 p11, T12 p12, T13 p13, T14 p14)
		{			
			TResult retval;
			
			if ((object)UnitOfWorkContext.Current == null)
			{
				using (UnitOfWorkContext unitOfWorkContext = Repository.GetUnitOfWorkContext())
				{
					retval = callbackMethod(unitOfWorkContext, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14);
											
					unitOfWorkContext.Complete();
					
					return retval;
				}
			}			
			else
			{
				return callbackMethod(UnitOfWorkContext.Current, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14);
			}
		}

		protected TResult ExecuteAmbientUnitOfWorkAware<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TResult>(Stank<UnitOfWorkContext, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TResult> callbackMethod, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9, T10 p10, T11 p11, T12 p12, T13 p13, T14 p14, T15 p15)
		{			
			TResult retval;
			
			if ((object)UnitOfWorkContext.Current == null)
			{
				using (UnitOfWorkContext unitOfWorkContext = Repository.GetUnitOfWorkContext())
				{
					retval = callbackMethod(unitOfWorkContext, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15);
											
					unitOfWorkContext.Complete();
					
					return retval;
				}
			}			
			else
			{
				return callbackMethod(UnitOfWorkContext.Current, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15);
			}
		}

		#endregion
	}
}
