//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 4.4.5.39286;
// 		Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;
using System.Collections.Generic;
using System.Data;
using System.Text;

using TextMetal.Core.ExpressionModel;
using TextMetal.Plumbing.CommonFacilities;

using Expression = TextMetal.Core.ExpressionModel.IExpressionXmlObject;
using NullaryExpression = TextMetal.Core.ExpressionModel.NullaryExpressionConstruct;
using UnaryExpression = TextMetal.Core.ExpressionModel.UnaryExpressionConstruct;
using BinaryExpression = TextMetal.Core.ExpressionModel.BinaryExpressionConstruct;
using Surface = TextMetal.Core.ExpressionModel.SurfaceConstruct;
using Value = TextMetal.Core.ExpressionModel.ValueConstruct;
using Container = TextMetal.Core.ExpressionModel.ExpressionContainerConstruct;

namespace TextMetal.WebHostSample.Objects.Model
{
	public partial class SqlExpressionVisitor : ExpressionVisitor
	{
		#region Constructors/Destructors

		public SqlExpressionVisitor(UnitOfWorkContext unitOfWorkContext, IList<IDataParameter> commandParameters)
		{
			if ((object)unitOfWorkContext == null)
				throw new ArgumentNullException("unitOfWorkContext");

			if ((object)commandParameters == null)
				throw new ArgumentNullException("commandParameters");

			this.unitOfWorkContext = unitOfWorkContext;
			this.commandParameters = commandParameters;
		}

		#endregion

		#region Fields/Constants

		private readonly IList<IDataParameter> commandParameters;
		private readonly StringBuilder strings = new StringBuilder();
		private readonly UnitOfWorkContext unitOfWorkContext;

		#endregion

		#region Properties/Indexers/Events

		private IList<IDataParameter> CommandParameters
		{
			get
			{
				return this.commandParameters;
			}
		}

		private StringBuilder Strings
		{
			get
			{
				return this.strings;
			}
		}

		private UnitOfWorkContext UnitOfWorkContext
		{
			get
			{
				return this.unitOfWorkContext;
			}
		}

		#endregion

		#region Methods/Operators

		public static string GetFilterText(UnitOfWorkContext unitOfWorkContext, IList<IDataParameter> commandParameters, Expression expression)
		{
			SqlExpressionVisitor expressionVisitor;
			string expressionText;

			if ((object)unitOfWorkContext == null)
				throw new ArgumentNullException("unitOfWorkContext");

			if ((object)commandParameters == null)
				throw new ArgumentNullException("commandParameters");

			if ((object)expression == null)
				throw new ArgumentNullException("expression");

			expressionVisitor = new SqlExpressionVisitor(unitOfWorkContext, commandParameters);
			expressionVisitor.Visit(expression);
			expressionText = expressionVisitor.Strings.ToString();

			return expressionText;
		}

		public static string GetSortText(UnitOfWorkContext unitOfWorkContext, IList<IDataParameter> dataParameters, Order[] orders)
		{
			string expressionText;
			List<string> sortNames;
			
			sortNames = new List<string>();

			if ((object)orders != null)
			{
				foreach (Order order in orders)
				{
					if ((object)order.Facet == null)
					{
						continue;
					}

					sortNames.Add(string.Format("{0} {1}", Repository.ConnectionSpecificGetAliasedColumnName("t0", order.Facet.Name), order.Ascending ? "ASC" : "DESC"));
				}
			}

			if (sortNames.Count <= 0)
				sortNames.Add("1");

			expressionText = string.Join(", ", sortNames.ToArray());

			return expressionText;
		}

		private static DbType InferDbTypeForClrType(Type clrType)
		{
			if ((object)clrType == null)
				throw new ArgumentNullException("clrType");

			if (clrType.IsByRef /* || type.IsPointer || type.IsArray */)
				return InferDbTypeForClrType(clrType.GetElementType());
			else if (clrType.IsGenericType &&
			         clrType.GetGenericTypeDefinition() == typeof(Nullable<>))
				return InferDbTypeForClrType(Nullable.GetUnderlyingType(clrType));
			else if (clrType.IsEnum)
				return InferDbTypeForClrType(Enum.GetUnderlyingType(clrType));
			else if (clrType == typeof(Boolean))
				return DbType.Boolean;
			else if (clrType == typeof(Byte))
				return DbType.Byte;
			else if (clrType == typeof(DateTime))
				return DbType.DateTime;
			else if (clrType == typeof(DateTimeOffset))
				return DbType.DateTimeOffset;
			else if (clrType == typeof(Decimal))
				return DbType.Decimal;
			else if (clrType == typeof(Double))
				return DbType.Double;
			else if (clrType == typeof(Guid))
				return DbType.Guid;
			else if (clrType == typeof(Int16))
				return DbType.Int16;
			else if (clrType == typeof(Int32))
				return DbType.Int32;
			else if (clrType == typeof(Int64))
				return DbType.Int64;
			else if (clrType == typeof(SByte))
				return DbType.SByte;
			else if (clrType == typeof(Single))
				return DbType.Single;
			else if (clrType == typeof(UInt16))
				return DbType.UInt16;
			else if (clrType == typeof(UInt32))
				return DbType.UInt32;
			else if (clrType == typeof(UInt64))
				return DbType.UInt64;
			else if (clrType == typeof(Byte[]))
				return DbType.Binary;
			else if (clrType == typeof(String))
				return DbType.String;
			else if (clrType == typeof(Object))
				return DbType.Object;
			else
				throw new InvalidOperationException(string.Format("Cannot infer parameter type from unsupported CLR type '{0}'.", clrType.FullName));
		}

		protected override Expression VisitBinary(BinaryExpression binaryExpression)
		{
			if ((object)binaryExpression == null)
				throw new ArgumentNullException("binaryExpression");

			this.Strings.Append("(");

			this.Visit(binaryExpression.LeftExpression);

			switch (binaryExpression.BinaryOperator)
			{
				case BinaryOperator.Add:
					this.Strings.Append(" + ");
					break;
				case BinaryOperator.Sub:
					this.Strings.Append(" - ");
					break;
				case BinaryOperator.Div:
					this.Strings.Append(" / ");
					break;
				case BinaryOperator.Mul:
					this.Strings.Append(" * ");
					break;
				case BinaryOperator.Mod:
					this.Strings.Append(" % ");
					break;
				case BinaryOperator.And:
					this.Strings.Append(" AND ");
					break;
				case BinaryOperator.Or:
					this.Strings.Append(" OR ");
					break;
				case BinaryOperator.Eq:
					this.Strings.Append(" = ");
					break;
				case BinaryOperator.Ne:
					this.Strings.Append(" <> ");
					break;
				case BinaryOperator.Gt:
					this.Strings.Append(" > ");
					break;
				case BinaryOperator.Ge:
					this.Strings.Append(" >= ");
					break;
				case BinaryOperator.Lt:
					this.Strings.Append(" < ");
					break;
				case BinaryOperator.Le:
					this.Strings.Append(" <= ");
					break;
				case BinaryOperator.StrLk:
					this.Strings.Append(" LIKE ");
					break;
				case BinaryOperator.Band:
					this.Strings.Append(" & ");
					break;
				case BinaryOperator.Bor:
					this.Strings.Append(" | ");
					break;
				case BinaryOperator.Bxor:
					this.Strings.Append(" ^ ");
					break;
				default:
					throw new NotSupportedException(string.Format("The binary operator '{0}' is not supported.", binaryExpression.BinaryOperator));
			}

			this.Visit(binaryExpression.RightExpression);

			this.Strings.Append(")");

			return binaryExpression;
		}

		protected override Expression VisitContainer(Container container)
		{
			if ((object)container == null)
				throw new ArgumentNullException("container");

			if ((object)container.Content != null)
				this.Visit(container.Content);

			return container;
		}

		protected override Expression VisitNullary(NullaryExpression nullaryExpression)
		{
			if ((object)nullaryExpression == null)
				throw new ArgumentNullException("nullaryExpression");

			this.strings.Append(" (1 = 1) ");

			return nullaryExpression;
		}

		protected override Expression VisitSurface(Surface surface)
		{
			string columnName;

			if ((object)surface == null)
				throw new ArgumentNullException("surface");

			columnName = Repository.ConnectionSpecificGetAliasedColumnName("t0", surface.Name);

			this.Strings.Append(columnName);

			return surface;
		}

		protected override Expression VisitUnary(UnaryExpression unaryExpression)
		{
			if ((object)unaryExpression == null)
				throw new ArgumentNullException("unaryExpression");

			switch (unaryExpression.UnaryOperator)
			{
				case UnaryOperator.Not:
					this.strings.Append(" NOT ");
					this.Visit(unaryExpression.TheExpression);
					break;
				case UnaryOperator.IsNull:
					this.Visit(unaryExpression.TheExpression);
					this.strings.Append(" IS NULL ");
					break;
				case UnaryOperator.IsNotNull:
					this.Visit(unaryExpression.TheExpression);
					this.strings.Append(" IS NOT NULL ");
					break;
				case UnaryOperator.Neg:
					this.strings.Append(" - ");
					this.Visit(unaryExpression.TheExpression);
					break;
				case UnaryOperator.Pos:
					this.strings.Append(" + ");
					this.Visit(unaryExpression.TheExpression);
					break;
				case UnaryOperator.Incr:
					this.strings.Append(" (");
					this.Visit(unaryExpression.TheExpression);
					this.strings.Append(" + 1) ");
					break;
				case UnaryOperator.Decr:
					this.strings.Append(" (");
					this.Visit(unaryExpression.TheExpression);
					this.strings.Append(" - 1) ");
					break;
				case UnaryOperator.BComp:
					this.strings.Append(" ~ ");
					this.Visit(unaryExpression.TheExpression);
					break;
				default:
					throw new NotSupportedException(string.Format("The unary operator '{0}' is not supported.", unaryExpression.UnaryOperator));
			}

			return unaryExpression;
		}

		protected override Expression VisitUnknown(Expression expression)
		{
			if ((object)expression == null)
				throw new ArgumentNullException("expression");

			throw new NotSupportedException(string.Format("The unknown expression of type '{0}' is not supported.", expression.GetType()));
		}

		protected override Expression VisitValue(Value value)
		{
			IDataParameter commandParameter;
			string parameterName;
			Type valueType;

			if ((object)value == null)
				throw new ArgumentNullException("value");

			if ((object)value.__ == null)
				throw new InvalidOperationException("Cannot use the constant value NULL as a value operand; use UnaryExpression(..., UnaryOperator.IsNull) instead.");

			parameterName = Repository.ConnectionSpecificGetParameterName(string.Format("expr_{0}", Guid.NewGuid().ToString("N")));
			valueType = value.__.GetType();

			commandParameter = this.UnitOfWorkContext.CreateParameter(ParameterDirection.Input, InferDbTypeForClrType(valueType), 0, 0, 0, true, parameterName, value.__);
			this.commandParameters.Add(commandParameter);

			this.strings.Append(parameterName);

			return value;
		}

		#endregion
	}
}
