//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 4.3.0.26144;
// 		Copyright ©2002-2011 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: http://code.google.com/p/textmetal/
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2011 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;

using TextMetal.Core.Plumbing;

namespace TextMetal.WebHostSample.Objects.Model.Tables
{
	public partial class EmailMessage_Query : EmailMessage
	{		
		#region Constructors/Destructors
		
		public EmailMessage_Query()
		{
		}
		
		#endregion
		
		#region Fields/Constants

		private bool? @sortAscendingFrom;
		private bool? @isNullFrom;
		private bool? @sortAscendingSender;
		private bool? @isNullSender;
		private bool? @sortAscendingReplyTo;
		private bool? @isNullReplyTo;
		private bool? @sortAscendingTo;
		private bool? @isNullTo;
		private bool? @sortAscendingCc;
		private bool? @isNullCc;
		private bool? @sortAscendingBcc;
		private bool? @isNullBcc;
		private bool? @sortAscendingSubject;
		private bool? @isNullSubject;
		private bool? @sortAscendingIsBodyHtml;
		private bool? @isNullIsBodyHtml;
		private bool? @sortAscendingBody;
		private bool? @isNullBody;
		private bool? @sortAscendingProcessed;
		private bool? @isNullProcessed;
		private bool? @sortAscendingCreationTimestamp;
		private bool? @isNullCreationTimestamp;
		private bool? @sortAscendingModificationTimestamp;
		private bool? @isNullModificationTimestamp;
		private bool? @sortAscendingLogicalDelete;
		private bool? @isNullLogicalDelete;

		#endregion

		#region Properties/Indexers/Events

		public bool? SortAscendingFrom
		{
			get
			{
				return this.@sortAscendingFrom;
			}
			set
			{
				this.@sortAscendingFrom = value;
			}
		}
		
		public bool? IsNullFrom
		{
			get
			{
				return this.@isNullFrom;
			}
			set
			{
				this.@isNullFrom = value;
			}
		}
		
		public bool? SortAscendingSender
		{
			get
			{
				return this.@sortAscendingSender;
			}
			set
			{
				this.@sortAscendingSender = value;
			}
		}
		
		public bool? IsNullSender
		{
			get
			{
				return this.@isNullSender;
			}
			set
			{
				this.@isNullSender = value;
			}
		}
		
		public bool? SortAscendingReplyTo
		{
			get
			{
				return this.@sortAscendingReplyTo;
			}
			set
			{
				this.@sortAscendingReplyTo = value;
			}
		}
		
		public bool? IsNullReplyTo
		{
			get
			{
				return this.@isNullReplyTo;
			}
			set
			{
				this.@isNullReplyTo = value;
			}
		}
		
		public bool? SortAscendingTo
		{
			get
			{
				return this.@sortAscendingTo;
			}
			set
			{
				this.@sortAscendingTo = value;
			}
		}
		
		public bool? IsNullTo
		{
			get
			{
				return this.@isNullTo;
			}
			set
			{
				this.@isNullTo = value;
			}
		}
		
		public bool? SortAscendingCc
		{
			get
			{
				return this.@sortAscendingCc;
			}
			set
			{
				this.@sortAscendingCc = value;
			}
		}
		
		public bool? IsNullCc
		{
			get
			{
				return this.@isNullCc;
			}
			set
			{
				this.@isNullCc = value;
			}
		}
		
		public bool? SortAscendingBcc
		{
			get
			{
				return this.@sortAscendingBcc;
			}
			set
			{
				this.@sortAscendingBcc = value;
			}
		}
		
		public bool? IsNullBcc
		{
			get
			{
				return this.@isNullBcc;
			}
			set
			{
				this.@isNullBcc = value;
			}
		}
		
		public bool? SortAscendingSubject
		{
			get
			{
				return this.@sortAscendingSubject;
			}
			set
			{
				this.@sortAscendingSubject = value;
			}
		}
		
		public bool? IsNullSubject
		{
			get
			{
				return this.@isNullSubject;
			}
			set
			{
				this.@isNullSubject = value;
			}
		}
		
		public bool? SortAscendingIsBodyHtml
		{
			get
			{
				return this.@sortAscendingIsBodyHtml;
			}
			set
			{
				this.@sortAscendingIsBodyHtml = value;
			}
		}
		
		public bool? IsNullIsBodyHtml
		{
			get
			{
				return this.@isNullIsBodyHtml;
			}
			set
			{
				this.@isNullIsBodyHtml = value;
			}
		}
		
		public bool? SortAscendingBody
		{
			get
			{
				return this.@sortAscendingBody;
			}
			set
			{
				this.@sortAscendingBody = value;
			}
		}
		
		public bool? IsNullBody
		{
			get
			{
				return this.@isNullBody;
			}
			set
			{
				this.@isNullBody = value;
			}
		}
		
		public bool? SortAscendingProcessed
		{
			get
			{
				return this.@sortAscendingProcessed;
			}
			set
			{
				this.@sortAscendingProcessed = value;
			}
		}
		
		public bool? IsNullProcessed
		{
			get
			{
				return this.@isNullProcessed;
			}
			set
			{
				this.@isNullProcessed = value;
			}
		}
		
		public bool? SortAscendingCreationTimestamp
		{
			get
			{
				return this.@sortAscendingCreationTimestamp;
			}
			set
			{
				this.@sortAscendingCreationTimestamp = value;
			}
		}
		
		public bool? IsNullCreationTimestamp
		{
			get
			{
				return this.@isNullCreationTimestamp;
			}
			set
			{
				this.@isNullCreationTimestamp = value;
			}
		}
		
		public bool? SortAscendingModificationTimestamp
		{
			get
			{
				return this.@sortAscendingModificationTimestamp;
			}
			set
			{
				this.@sortAscendingModificationTimestamp = value;
			}
		}
		
		public bool? IsNullModificationTimestamp
		{
			get
			{
				return this.@isNullModificationTimestamp;
			}
			set
			{
				this.@isNullModificationTimestamp = value;
			}
		}
		
		public bool? SortAscendingLogicalDelete
		{
			get
			{
				return this.@sortAscendingLogicalDelete;
			}
			set
			{
				this.@sortAscendingLogicalDelete = value;
			}
		}
		
		public bool? IsNullLogicalDelete
		{
			get
			{
				return this.@isNullLogicalDelete;
			}
			set
			{
				this.@isNullLogicalDelete = value;
			}
		}
		
		#endregion
	}
}
