//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 4.3.0.27741;
// 		Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: http://code.google.com/p/textmetal/
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;

using TextMetal.Core.Plumbing;

namespace TextMetal.WebHostSample.Objects.Model.Tables
{
	public partial class EmailAttachment_Query : EmailAttachment
	{		
		#region Constructors/Destructors
		
		public EmailAttachment_Query()
		{
		}
		
		#endregion
		
		#region Fields/Constants

		private bool? @sortAscendingEmailMessageId;
		private bool? @isNullEmailMessageId;
		private bool? @sortAscendingMimeType;
		private bool? @isNullMimeType;
		private bool? @sortAscendingAttachmentBits;
		private bool? @isNullAttachmentBits;
		private bool? @sortAscendingCreationTimestamp;
		private bool? @isNullCreationTimestamp;
		private bool? @sortAscendingModificationTimestamp;
		private bool? @isNullModificationTimestamp;
		private bool? @sortAscendingLogicalDelete;
		private bool? @isNullLogicalDelete;

		#endregion

		#region Properties/Indexers/Events

		public bool? SortAscendingEmailMessageId
		{
			get
			{
				return this.@sortAscendingEmailMessageId;
			}
			set
			{
				this.@sortAscendingEmailMessageId = value;
			}
		}
		
		public bool? IsNullEmailMessageId
		{
			get
			{
				return this.@isNullEmailMessageId;
			}
			set
			{
				this.@isNullEmailMessageId = value;
			}
		}
		
		public bool? SortAscendingMimeType
		{
			get
			{
				return this.@sortAscendingMimeType;
			}
			set
			{
				this.@sortAscendingMimeType = value;
			}
		}
		
		public bool? IsNullMimeType
		{
			get
			{
				return this.@isNullMimeType;
			}
			set
			{
				this.@isNullMimeType = value;
			}
		}
		
		public bool? SortAscendingAttachmentBits
		{
			get
			{
				return this.@sortAscendingAttachmentBits;
			}
			set
			{
				this.@sortAscendingAttachmentBits = value;
			}
		}
		
		public bool? IsNullAttachmentBits
		{
			get
			{
				return this.@isNullAttachmentBits;
			}
			set
			{
				this.@isNullAttachmentBits = value;
			}
		}
		
		public bool? SortAscendingCreationTimestamp
		{
			get
			{
				return this.@sortAscendingCreationTimestamp;
			}
			set
			{
				this.@sortAscendingCreationTimestamp = value;
			}
		}
		
		public bool? IsNullCreationTimestamp
		{
			get
			{
				return this.@isNullCreationTimestamp;
			}
			set
			{
				this.@isNullCreationTimestamp = value;
			}
		}
		
		public bool? SortAscendingModificationTimestamp
		{
			get
			{
				return this.@sortAscendingModificationTimestamp;
			}
			set
			{
				this.@sortAscendingModificationTimestamp = value;
			}
		}
		
		public bool? IsNullModificationTimestamp
		{
			get
			{
				return this.@isNullModificationTimestamp;
			}
			set
			{
				this.@isNullModificationTimestamp = value;
			}
		}
		
		public bool? SortAscendingLogicalDelete
		{
			get
			{
				return this.@sortAscendingLogicalDelete;
			}
			set
			{
				this.@sortAscendingLogicalDelete = value;
			}
		}
		
		public bool? IsNullLogicalDelete
		{
			get
			{
				return this.@isNullLogicalDelete;
			}
			set
			{
				this.@isNullLogicalDelete = value;
			}
		}
		
		#endregion
	}
}
