//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 4.4.5.2714;
// 		Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;

using NUnit.Framework;
using TextMetal.WebHostSample.Objects.Model.Procedures;

namespace TextMetal.WebHostSample.Objects.Model.IntegrationTests
{
	[TestFixture]
	public partial class RepositoryTests
	{		
		#region Constructors/Destructors
		
		public RepositoryTests()
		{
		}
		
		#endregion
		
		#region Methods/Operators
		
		[TestFixtureSetUp]
		public void TestFixtureSetUp()
		{
			Repository.InitDatabase();
		}

		[TestFixtureTearDown]
		public void TestFixtureTearDown()
		{
		}

		#endregion
	}
}
