//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 4.4.5.2714;
// 		Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;

using NUnit.Framework;

using TestingFramework.Core.Customization;

using TextMetal.WebHostSample.Objects.Model.Tables;

namespace TextMetal.WebHostSample.Objects.Model.UnitTests.Tables
{
	[TestFixture]
	public sealed class EventLogTests
	{		
		#region Constructors/Destructors
		
		public EventLogTests()
		{
		}
		
		#endregion
		
		#region Methods/Operators
		
		[Test]
		public void ShouldCreateEventLogTest()
		{			
			EventLog eventLog;
			
			eventLog = new EventLog();

			eventLog.@EventLogId = ValueGenerator.GetNextValue<Int32>();
			Assert.AreEqual(ValueGenerator.GetPreviousValue<Int32>(), eventLog.@EventLogId);

			eventLog.@EventText = ValueGenerator.GetNextValue<String>();
			Assert.AreEqual(ValueGenerator.GetPreviousValue<String>(), eventLog.@EventText);

			eventLog.@CreationTimestamp = ValueGenerator.GetNextValue<DateTime>();
			Assert.AreEqual(ValueGenerator.GetPreviousValue<DateTime>(), eventLog.@CreationTimestamp);

			eventLog.@ModificationTimestamp = ValueGenerator.GetNextValue<DateTime>();
			Assert.AreEqual(ValueGenerator.GetPreviousValue<DateTime>(), eventLog.@ModificationTimestamp);

			eventLog.@LogicalDelete = ValueGenerator.GetNextValue<Boolean>();
			Assert.AreEqual(ValueGenerator.GetPreviousValue<Boolean>(), eventLog.@LogicalDelete);
		}
		
		#endregion
	}
}
