//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 4.4.5.2714;
// 		Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;
using System.Collections.Generic;
using System.Xml.Serialization;

using TextMetal.Core;
using TextMetal.Plumbing.CommonFacilities;

namespace TextMetal.WebHostSample.Objects.Model
{
	/// <summary>
	/// 	Represents a single historical revsion to a database (file).
	/// </summary>
	[Serializable]
	public partial class DatabaseRevision
	{
		#region Constructors/Destructors

		/// <summary>
		/// 	Initializes a new instance of the DatabaseRevision class.
		/// </summary>
		public DatabaseRevision()
		{
		}

		#endregion

		#region Fields/Constants

		private readonly List<string> statements = new List<string>();
		private int number;

		#endregion

		#region Properties/Indexers/Events

		/// <summary>
		/// 	Gets or sets the revision number.
		/// </summary>
		[XmlAttribute("number")]
		public int Number
		{
			get
			{
				return this.number;
			}
			set
			{
				this.number = value;
			}
		}

		/// <summary>
		/// 	Gets an ordered list of statements to execute for this revision.
		/// </summary>
		[XmlArray(ElementName = "Statements")]
		[XmlArrayItem(ElementName = "Statement")]
		public List<string> Statements
		{
			get
			{
				return this.statements;
			}
		}

		#endregion
	}
}
