//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 4.4.5.2714;
// 		Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;
using System.Data;

using TextMetal.Plumbing.CommonFacilities;

namespace TextMetal.WebHostSample.Objects.Model
{
	public partial class Repository
	{		
		#region Fields/Constants
		
		private const int SQL_SERVER_PERSIST_NOT_EXPECTED_RECORDS_AFFECTED = 0;
		private const int SQL_SERVER_QUERY_EXPECTED_RECORDS_AFFECTED = -1;
		private const string SQL_SERVER_IDENTITY_COMMAND = "@@IDENTITY"; // warning: 'SELECT SCOPE_IDENTITY() AS PK' should be used in the SAME BATCH if there is any chance of triggers on any tables causing identity creation

		private const string SQL_SERVER_COLUMN_ALIASED_FORMAT = "{0}.[{1}]";
		private const string SQL_SERVER_COLUMN_NAME_FORMAT = "[{0}]";
		private const string SQL_SERVER_PARAMETER_NAME_FORMAT = "@{0}";
		private const string SQL_SERVER_SCHEMA_TABLE_NAME_FORMAT = "[{0}].[{1}]";
		private const string SQL_SERVER_TABLE_ALIAS_FORMAT = "{0}";
		private const string SQL_SERVER_TABLE_NAME_FORMAT = "[{0}]";

		#endregion

		#region Methods/Operators
		
		private static string SqlServerSpecificGetIdentityCommand()
		{
			string retVal;

			retVal = SQL_SERVER_IDENTITY_COMMAND;

			return retVal;
		}

		private static string SqlServerSpecificGetTableName(string schemaName, string tableName)
		{
			string retVal;

			retVal = !DataType.IsNullOrWhiteSpace(schemaName) ?
				string.Format(SQL_SERVER_SCHEMA_TABLE_NAME_FORMAT, schemaName, tableName) :
				string.Format(SQL_SERVER_TABLE_NAME_FORMAT, tableName);

			return retVal;
		}

		private static string SqlServerSpecificGetTableAlias(string tableAlias)
		{
			string retVal;

			retVal = string.Format(SQL_SERVER_TABLE_ALIAS_FORMAT, tableAlias);

			return retVal;
		}

		private static string SqlServerSpecificGetParameterName(string parameterName)
		{
			string retVal;

			retVal = string.Format(SQL_SERVER_PARAMETER_NAME_FORMAT, parameterName);

			return retVal;
		}

		private static string SqlServerSpecificGetColumnName(string columnName)
		{
			string retVal;

			retVal = string.Format(SQL_SERVER_COLUMN_NAME_FORMAT, columnName);

			return retVal;
		}

		private static string SqlServerSpecificGetAliasedColumnName(string tableAlias, string columnName)
		{
			string retVal;

			retVal = string.Format(SQL_SERVER_COLUMN_ALIASED_FORMAT, SqlServerSpecificGetTableAlias(tableAlias), columnName);

			return retVal;
		}

		private static void SqlServerSpecificParameterMagic(UnitOfWorkContext unitOfWorkContext, IDataParameter commandParameter, string generatedFromColumnNativeType)
		{
			if ((object)unitOfWorkContext == null)
				throw new ArgumentNullException("unitOfWorkContext");

			if ((object)commandParameter == null)
				throw new ArgumentNullException("commandParameter");

			if (generatedFromColumnNativeType == "ntext")
				Reflexion.SetLogicalPropertyValue(commandParameter, "SqlDbType", Enum.Parse(Type.GetType("System.Data.SqlDbType, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089", true), "NText", true));
			else if (generatedFromColumnNativeType == "text")
				Reflexion.SetLogicalPropertyValue(commandParameter, "SqlDbType", Enum.Parse(Type.GetType("System.Data.SqlDbType, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089", true), "Text", true));
			else if (generatedFromColumnNativeType == "image")
				Reflexion.SetLogicalPropertyValue(commandParameter, "SqlDbType", Enum.Parse(Type.GetType("System.Data.SqlDbType, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089", true), "Image", true));
		}

		#endregion
	}
}
