#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextMetal.HostImpl.AspNetSample.Objects.Model.L2S
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TextMetalWebHostSample")]
	public partial class TxtMtlPrimaryDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEmailAttachment(EmailAttachment instance);
    partial void UpdateEmailAttachment(EmailAttachment instance);
    partial void DeleteEmailAttachment(EmailAttachment instance);
    partial void InsertEmailMessage(EmailMessage instance);
    partial void UpdateEmailMessage(EmailMessage instance);
    partial void DeleteEmailMessage(EmailMessage instance);
    partial void InsertEventLog(EventLog instance);
    partial void UpdateEventLog(EventLog instance);
    partial void DeleteEventLog(EventLog instance);
    #endregion
		
		public TxtMtlPrimaryDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TxtMtlPrimaryDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TxtMtlPrimaryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TxtMtlPrimaryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<EmailAttachment> EmailAttachments
		{
			get
			{
				return this.GetTable<EmailAttachment>();
			}
		}
		
		public System.Data.Linq.Table<EmailMessage> EmailMessages
		{
			get
			{
				return this.GetTable<EmailMessage>();
			}
		}
		
		public System.Data.Linq.Table<EventLog> EventLogs
		{
			get
			{
				return this.GetTable<EventLog>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EmailAttachment")]
	public partial class EmailAttachment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _EmailAttachmentId;
		
		private System.Nullable<int> _EmailMessageId;
		
		private string _MimeType;
		
		private System.Data.Linq.Binary _AttachmentBits;
		
		private System.Nullable<System.DateTime> _CreationTimestamp;
		
		private System.Nullable<System.DateTime> _ModificationTimestamp;
		
		private System.Nullable<bool> _LogicalDelete;
		
		private EntityRef<EmailMessage> _EmailMessage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmailAttachmentIdChanging(System.Nullable<int> value);
    partial void OnEmailAttachmentIdChanged();
    partial void OnEmailMessageIdChanging(System.Nullable<int> value);
    partial void OnEmailMessageIdChanged();
    partial void OnMimeTypeChanging(string value);
    partial void OnMimeTypeChanged();
    partial void OnAttachmentBitsChanging(System.Data.Linq.Binary value);
    partial void OnAttachmentBitsChanged();
    partial void OnCreationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimestampChanged();
    partial void OnModificationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnModificationTimestampChanged();
    partial void OnLogicalDeleteChanging(System.Nullable<bool> value);
    partial void OnLogicalDeleteChanged();
    #endregion
		
		public EmailAttachment()
		{
			this._EmailMessage = default(EntityRef<EmailMessage>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAttachmentId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public System.Nullable<int> EmailAttachmentId
		{
			get
			{
				return this._EmailAttachmentId;
			}
			set
			{
				if ((this._EmailAttachmentId != value))
				{
					this.OnEmailAttachmentIdChanging(value);
					this.SendPropertyChanging();
					this._EmailAttachmentId = value;
					this.SendPropertyChanged("EmailAttachmentId");
					this.OnEmailAttachmentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailMessageId", DbType="Int NOT NULL")]
		public System.Nullable<int> EmailMessageId
		{
			get
			{
				return this._EmailMessageId;
			}
			set
			{
				if ((this._EmailMessageId != value))
				{
					if (this._EmailMessage.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmailMessageIdChanging(value);
					this.SendPropertyChanging();
					this._EmailMessageId = value;
					this.SendPropertyChanged("EmailMessageId");
					this.OnEmailMessageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MimeType", DbType="NVarChar(2047) NOT NULL")]
		public string MimeType
		{
			get
			{
				return this._MimeType;
			}
			set
			{
				if ((this._MimeType != value))
				{
					this.OnMimeTypeChanging(value);
					this.SendPropertyChanging();
					this._MimeType = value;
					this.SendPropertyChanged("MimeType");
					this.OnMimeTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttachmentBits", DbType="Image NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary AttachmentBits
		{
			get
			{
				return this._AttachmentBits;
			}
			set
			{
				if ((this._AttachmentBits != value))
				{
					this.OnAttachmentBitsChanging(value);
					this.SendPropertyChanging();
					this._AttachmentBits = value;
					this.SendPropertyChanged("AttachmentBits");
					this.OnAttachmentBitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimestamp", DbType="DateTime NOT NULL")]
		public System.Nullable<System.DateTime> CreationTimestamp
		{
			get
			{
				return this._CreationTimestamp;
			}
			set
			{
				if ((this._CreationTimestamp != value))
				{
					this.OnCreationTimestampChanging(value);
					this.SendPropertyChanging();
					this._CreationTimestamp = value;
					this.SendPropertyChanged("CreationTimestamp");
					this.OnCreationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificationTimestamp", DbType="DateTime NOT NULL")]
		public System.Nullable<System.DateTime> ModificationTimestamp
		{
			get
			{
				return this._ModificationTimestamp;
			}
			set
			{
				if ((this._ModificationTimestamp != value))
				{
					this.OnModificationTimestampChanging(value);
					this.SendPropertyChanging();
					this._ModificationTimestamp = value;
					this.SendPropertyChanged("ModificationTimestamp");
					this.OnModificationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogicalDelete", DbType="Bit NOT NULL")]
		public System.Nullable<bool> LogicalDelete
		{
			get
			{
				return this._LogicalDelete;
			}
			set
			{
				if ((this._LogicalDelete != value))
				{
					this.OnLogicalDeleteChanging(value);
					this.SendPropertyChanging();
					this._LogicalDelete = value;
					this.SendPropertyChanged("LogicalDelete");
					this.OnLogicalDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EmailMessage_EmailAttachment", Storage="_EmailMessage", ThisKey="EmailMessageId", OtherKey="EmailMessageId", IsForeignKey=true)]
		public EmailMessage EmailMessage
		{
			get
			{
				return this._EmailMessage.Entity;
			}
			set
			{
				EmailMessage previousValue = this._EmailMessage.Entity;
				if (((previousValue != value) 
							|| (this._EmailMessage.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EmailMessage.Entity = null;
						previousValue.EmailAttachments.Remove(this);
					}
					this._EmailMessage.Entity = value;
					if ((value != null))
					{
						value.EmailAttachments.Add(this);
						this._EmailMessageId = value.EmailMessageId;
					}
					else
					{
						this._EmailMessageId = default(Nullable<int>);
					}
					this.SendPropertyChanged("EmailMessage");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EmailMessage")]
	public partial class EmailMessage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _EmailMessageId;
		
		private string _From;
		
		private string _Sender;
		
		private string _ReplyTo;
		
		private string _To;
		
		private string _Cc;
		
		private string _Bcc;
		
		private string _Subject;
		
		private System.Nullable<bool> _IsBodyHtml;
		
		private string _Body;
		
		private System.Nullable<bool> _Processed;
		
		private System.Nullable<System.DateTime> _CreationTimestamp;
		
		private System.Nullable<System.DateTime> _ModificationTimestamp;
		
		private System.Nullable<bool> _LogicalDelete;
		
		private EntitySet<EmailAttachment> _EmailAttachments;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmailMessageIdChanging(System.Nullable<int> value);
    partial void OnEmailMessageIdChanged();
    partial void OnFromChanging(string value);
    partial void OnFromChanged();
    partial void OnSenderChanging(string value);
    partial void OnSenderChanged();
    partial void OnReplyToChanging(string value);
    partial void OnReplyToChanged();
    partial void OnToChanging(string value);
    partial void OnToChanged();
    partial void OnCcChanging(string value);
    partial void OnCcChanged();
    partial void OnBccChanging(string value);
    partial void OnBccChanged();
    partial void OnSubjectChanging(string value);
    partial void OnSubjectChanged();
    partial void OnIsBodyHtmlChanging(System.Nullable<bool> value);
    partial void OnIsBodyHtmlChanged();
    partial void OnBodyChanging(string value);
    partial void OnBodyChanged();
    partial void OnProcessedChanging(System.Nullable<bool> value);
    partial void OnProcessedChanged();
    partial void OnCreationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimestampChanged();
    partial void OnModificationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnModificationTimestampChanged();
    partial void OnLogicalDeleteChanging(System.Nullable<bool> value);
    partial void OnLogicalDeleteChanged();
    #endregion
		
		public EmailMessage()
		{
			this._EmailAttachments = new EntitySet<EmailAttachment>(new Action<EmailAttachment>(this.attach_EmailAttachments), new Action<EmailAttachment>(this.detach_EmailAttachments));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailMessageId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public System.Nullable<int> EmailMessageId
		{
			get
			{
				return this._EmailMessageId;
			}
			set
			{
				if ((this._EmailMessageId != value))
				{
					this.OnEmailMessageIdChanging(value);
					this.SendPropertyChanging();
					this._EmailMessageId = value;
					this.SendPropertyChanged("EmailMessageId");
					this.OnEmailMessageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From", DbType="NVarChar(2047) NOT NULL")]
		public string From
		{
			get
			{
				return this._From;
			}
			set
			{
				if ((this._From != value))
				{
					this.OnFromChanging(value);
					this.SendPropertyChanging();
					this._From = value;
					this.SendPropertyChanged("From");
					this.OnFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sender", DbType="NVarChar(2047)")]
		public string Sender
		{
			get
			{
				return this._Sender;
			}
			set
			{
				if ((this._Sender != value))
				{
					this.OnSenderChanging(value);
					this.SendPropertyChanging();
					this._Sender = value;
					this.SendPropertyChanged("Sender");
					this.OnSenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReplyTo", DbType="NVarChar(2047)")]
		public string ReplyTo
		{
			get
			{
				return this._ReplyTo;
			}
			set
			{
				if ((this._ReplyTo != value))
				{
					this.OnReplyToChanging(value);
					this.SendPropertyChanging();
					this._ReplyTo = value;
					this.SendPropertyChanged("ReplyTo");
					this.OnReplyToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To", DbType="NVarChar(2047) NOT NULL")]
		public string To
		{
			get
			{
				return this._To;
			}
			set
			{
				if ((this._To != value))
				{
					this.OnToChanging(value);
					this.SendPropertyChanging();
					this._To = value;
					this.SendPropertyChanged("To");
					this.OnToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CC", Storage="_Cc", DbType="NVarChar(2047)")]
		public string Cc
		{
			get
			{
				return this._Cc;
			}
			set
			{
				if ((this._Cc != value))
				{
					this.OnCcChanging(value);
					this.SendPropertyChanging();
					this._Cc = value;
					this.SendPropertyChanged("Cc");
					this.OnCcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="BCC", Storage="_Bcc", DbType="NVarChar(2047)")]
		public string Bcc
		{
			get
			{
				return this._Bcc;
			}
			set
			{
				if ((this._Bcc != value))
				{
					this.OnBccChanging(value);
					this.SendPropertyChanging();
					this._Bcc = value;
					this.SendPropertyChanged("Bcc");
					this.OnBccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="NVarChar(2047) NOT NULL")]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this.OnSubjectChanging(value);
					this.SendPropertyChanging();
					this._Subject = value;
					this.SendPropertyChanged("Subject");
					this.OnSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBodyHtml", DbType="Bit NOT NULL")]
		public System.Nullable<bool> IsBodyHtml
		{
			get
			{
				return this._IsBodyHtml;
			}
			set
			{
				if ((this._IsBodyHtml != value))
				{
					this.OnIsBodyHtmlChanging(value);
					this.SendPropertyChanging();
					this._IsBodyHtml = value;
					this.SendPropertyChanged("IsBodyHtml");
					this.OnIsBodyHtmlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Body", DbType="NText NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public string Body
		{
			get
			{
				return this._Body;
			}
			set
			{
				if ((this._Body != value))
				{
					this.OnBodyChanging(value);
					this.SendPropertyChanging();
					this._Body = value;
					this.SendPropertyChanged("Body");
					this.OnBodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Processed", DbType="Bit NOT NULL")]
		public System.Nullable<bool> Processed
		{
			get
			{
				return this._Processed;
			}
			set
			{
				if ((this._Processed != value))
				{
					this.OnProcessedChanging(value);
					this.SendPropertyChanging();
					this._Processed = value;
					this.SendPropertyChanged("Processed");
					this.OnProcessedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimestamp", DbType="DateTime NOT NULL")]
		public System.Nullable<System.DateTime> CreationTimestamp
		{
			get
			{
				return this._CreationTimestamp;
			}
			set
			{
				if ((this._CreationTimestamp != value))
				{
					this.OnCreationTimestampChanging(value);
					this.SendPropertyChanging();
					this._CreationTimestamp = value;
					this.SendPropertyChanged("CreationTimestamp");
					this.OnCreationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificationTimestamp", DbType="DateTime NOT NULL")]
		public System.Nullable<System.DateTime> ModificationTimestamp
		{
			get
			{
				return this._ModificationTimestamp;
			}
			set
			{
				if ((this._ModificationTimestamp != value))
				{
					this.OnModificationTimestampChanging(value);
					this.SendPropertyChanging();
					this._ModificationTimestamp = value;
					this.SendPropertyChanged("ModificationTimestamp");
					this.OnModificationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogicalDelete", DbType="Bit NOT NULL")]
		public System.Nullable<bool> LogicalDelete
		{
			get
			{
				return this._LogicalDelete;
			}
			set
			{
				if ((this._LogicalDelete != value))
				{
					this.OnLogicalDeleteChanging(value);
					this.SendPropertyChanging();
					this._LogicalDelete = value;
					this.SendPropertyChanged("LogicalDelete");
					this.OnLogicalDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EmailMessage_EmailAttachment", Storage="_EmailAttachments", ThisKey="EmailMessageId", OtherKey="EmailMessageId")]
		public EntitySet<EmailAttachment> EmailAttachments
		{
			get
			{
				return this._EmailAttachments;
			}
			set
			{
				this._EmailAttachments.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EmailAttachments(EmailAttachment entity)
		{
			this.SendPropertyChanging();
			entity.EmailMessage = this;
		}
		
		private void detach_EmailAttachments(EmailAttachment entity)
		{
			this.SendPropertyChanging();
			entity.EmailMessage = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EventLog")]
	public partial class EventLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _EventLogId;
		
		private string _EventText;
		
		private System.Nullable<System.DateTime> _CreationTimestamp;
		
		private System.Nullable<System.DateTime> _ModificationTimestamp;
		
		private System.Nullable<bool> _LogicalDelete;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEventLogIdChanging(System.Nullable<int> value);
    partial void OnEventLogIdChanged();
    partial void OnEventTextChanging(string value);
    partial void OnEventTextChanged();
    partial void OnCreationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimestampChanged();
    partial void OnModificationTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnModificationTimestampChanged();
    partial void OnLogicalDeleteChanging(System.Nullable<bool> value);
    partial void OnLogicalDeleteChanged();
    #endregion
		
		public EventLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventLogId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public System.Nullable<int> EventLogId
		{
			get
			{
				return this._EventLogId;
			}
			set
			{
				if ((this._EventLogId != value))
				{
					this.OnEventLogIdChanging(value);
					this.SendPropertyChanging();
					this._EventLogId = value;
					this.SendPropertyChanged("EventLogId");
					this.OnEventLogIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventText", DbType="NText NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public string EventText
		{
			get
			{
				return this._EventText;
			}
			set
			{
				if ((this._EventText != value))
				{
					this.OnEventTextChanging(value);
					this.SendPropertyChanging();
					this._EventText = value;
					this.SendPropertyChanged("EventText");
					this.OnEventTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimestamp", DbType="DateTime NOT NULL")]
		public System.Nullable<System.DateTime> CreationTimestamp
		{
			get
			{
				return this._CreationTimestamp;
			}
			set
			{
				if ((this._CreationTimestamp != value))
				{
					this.OnCreationTimestampChanging(value);
					this.SendPropertyChanging();
					this._CreationTimestamp = value;
					this.SendPropertyChanged("CreationTimestamp");
					this.OnCreationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificationTimestamp", DbType="DateTime NOT NULL")]
		public System.Nullable<System.DateTime> ModificationTimestamp
		{
			get
			{
				return this._ModificationTimestamp;
			}
			set
			{
				if ((this._ModificationTimestamp != value))
				{
					this.OnModificationTimestampChanging(value);
					this.SendPropertyChanging();
					this._ModificationTimestamp = value;
					this.SendPropertyChanged("ModificationTimestamp");
					this.OnModificationTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogicalDelete", DbType="Bit NOT NULL")]
		public System.Nullable<bool> LogicalDelete
		{
			get
			{
				return this._LogicalDelete;
			}
			set
			{
				if ((this._LogicalDelete != value))
				{
					this.OnLogicalDeleteChanging(value);
					this.SendPropertyChanging();
					this._LogicalDelete = value;
					this.SendPropertyChanged("LogicalDelete");
					this.OnLogicalDeleteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
