//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 4.4.5.2714;
// 		Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;
using System.Collections.Generic;

namespace TextMetal.WebHostSample.Objects.Model.Procedures
{
	public sealed class BlahBlahBlah_Response
	{		
		#region Constructors/Destructors
		
		public BlahBlahBlah_Response()
		{
		}
		
		#endregion
		
		#region Fields/Constants
			
		private readonly IList<BlahBlahBlah_Result> results = new List<BlahBlahBlah_Result>();
		private String @j;
		private Int32 @returnValue;

		#endregion
			
		#region Properties/Indexers/Events
			
		public IList<BlahBlahBlah_Result> Results
		{
			get
			{
				return this.results;
			}
		}

		public String J
		{
			get
			{
				return this.@j;
			}
			set
			{
				this.@j = value;
			}
		}
		
		public Int32 ReturnValue
		{
			get
			{
				return this.@returnValue;
			}
			set
			{
				this.@returnValue = value;
			}
		}
		
		#endregion		
	}
}
