//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 4.4.5.2714;
// 		Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;

namespace TextMetal.WebHostSample.Objects.Model.Procedures
{
	public sealed class BlahBlahBlah_Request
	{		
		#region Constructors/Destructors
		
		public BlahBlahBlah_Request()
		{
		}
		
		#endregion
		
		#region Fields/Constants
		
		public const string SCHEMA_NAME_DBO = "dbo";
		public const string PROCEDURE_NAME_BLAHBLAHBLAHS = "BLAH_BLAH_BLAHS";
		
		public const string PARAMETER_NAME_I = "i";
		public const string PARAMETER_NAME_O = "o";
		public const string PARAMETER_NAME_J = "j";
		public const string PARAMETER_NAME_RETURN_VALUE = "ReturnValue";

		private Int32 @i;
		private Byte[] @o;
		private String @j;

		#endregion

		#region Properties/Indexers/Events

		public Int32 I
		{
			get
			{
				return this.@i;
			}
			set
			{
				this.@i = value;
			}
		}
		
		public Byte[] O
		{
			get
			{
				return this.@o;
			}
			set
			{
				this.@o = value;
			}
		}
		
		public String J
		{
			get
			{
				return this.@j;
			}
			set
			{
				this.@j = value;
			}
		}
		
		#endregion		
	}
}
