//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 4.4.5.2714;
// 		Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/
using System.Reflection;
using System.Runtime.InteropServices;

#if DEBUG

[assembly: AssemblyConfiguration("Debug")]
#else
[assembly: AssemblyConfiguration("Release")]
#endif

[assembly: AssemblyCompany("comapny")]
[assembly: AssemblyProduct("product")]
[assembly: AssemblyCopyright("©years company, all rights reserved.")]
[assembly: AssemblyDescription("description")]
[assembly: AssemblyTrademark("trademark™")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("0.0.0.*")]
[assembly: AssemblyInformationalVersion("yyyy.mm.dd")]
[assembly: AssemblyFileVersion("0.0.0.0")]
[assembly: AssemblyDelaySign(false)]
[assembly: ComVisible(false)]

