//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 4.4.5.2714;
// 		Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;

using NUnit.Framework;

using TextMetal.WebHostSample.Objects.Model.Tables;

namespace TextMetal.WebHostSample.Objects.Model.UnitTests
{
	[TestFixture]
	public partial class RepositoryTests
	{		
		#region Methods/Operators
		
		[Test]
		public void ShouldSaveEventLogTest()
		{
			throw new NotImplementedException();
		}
		
		[Test]
		public void ShouldLoadEventLogTest()
		{
			throw new NotImplementedException();
		}
		
		[Test]
		public void ShouldGetAllEventLogsTest()
		{
			throw new NotImplementedException();
		}

		[Test]
		public void ShouldSaveEmailMessageTest()
		{
			throw new NotImplementedException();
		}
		
		[Test]
		public void ShouldLoadEmailMessageTest()
		{
			throw new NotImplementedException();
		}
		
		[Test]
		public void ShouldGetAllEmailMessagesTest()
		{
			throw new NotImplementedException();
		}

		[Test]
		public void ShouldSaveEmailAttachmentTest()
		{
			throw new NotImplementedException();
		}
		
		[Test]
		public void ShouldLoadEmailAttachmentTest()
		{
			throw new NotImplementedException();
		}
		
		[Test]
		public void ShouldGetAllEmailAttachmentsTest()
		{
			throw new NotImplementedException();
		}

		#endregion
	}
}
