//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 4.4.5.2714;
// 		Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;

using NUnit.Framework;

using TestingFramework.Core.Customization;

using TextMetal.WebHostSample.Objects.Model.Procedures;

namespace TextMetal.WebHostSample.Objects.Model.UnitTests.Procedures
{
	[TestFixture]
	public sealed class BlahBlahBlah_ResultTests
	{		
		#region Constructors/Destructors
		
		public BlahBlahBlah_ResultTests()
		{
		}
		
		#endregion
			
		#region Methods/Operators
		
		[Test]
		public void ShouldCreateBlahBlahBlahTest()
		{			
			BlahBlahBlah_Result blahBlahBlahResult;
			
			blahBlahBlahResult = new BlahBlahBlah_Result();

			blahBlahBlahResult.@A = ValueGenerator.GetNextValue<Int32>();
			Assert.AreEqual(ValueGenerator.GetPreviousValue<Int32>(), blahBlahBlahResult.@A);

			blahBlahBlahResult.@B = ValueGenerator.GetNextValue<Int32>();
			Assert.AreEqual(ValueGenerator.GetPreviousValue<Int32>(), blahBlahBlahResult.@B);

			blahBlahBlahResult.@Iii = ValueGenerator.GetNextValue<Int32>();
			Assert.AreEqual(ValueGenerator.GetPreviousValue<Int32>(), blahBlahBlahResult.@Iii);

			blahBlahBlahResult.@Ooo = ValueGenerator.GetNextValue<Byte[]>();
			Assert.AreEqual(ValueGenerator.GetPreviousValue<Byte[]>(), blahBlahBlahResult.@Ooo);
		}
		
		#endregion
	}
}
