//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 4.4.5.2714;
// 		Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;

using NUnit.Framework;

using TestingFramework.Core.Customization;

using TextMetal.WebHostSample.Objects.Model.Procedures;

namespace TextMetal.WebHostSample.Objects.Model.UnitTests.Procedures
{
	[TestFixture]
	public sealed class BlahBlahBlah_RequestTests
	{		
		#region Constructors/Destructors
		
		public BlahBlahBlah_RequestTests()
		{
		}
		
		#endregion
			
		#region Methods/Operators
		
		[Test]
		public void ShouldCreateBlahBlahBlahTest()
		{			
			BlahBlahBlah_Request blahBlahBlahRequest;
			
			blahBlahBlahRequest = new BlahBlahBlah_Request();

			blahBlahBlahRequest.@I = ValueGenerator.GetNextValue<Int32>();
			Assert.AreEqual(ValueGenerator.GetPreviousValue<Int32>(), blahBlahBlahRequest.@I);

			blahBlahBlahRequest.@O = ValueGenerator.GetNextValue<Byte[]>();
			Assert.AreEqual(ValueGenerator.GetPreviousValue<Byte[]>(), blahBlahBlahRequest.@O);

			blahBlahBlahRequest.@J = ValueGenerator.GetNextValue<String>();
			Assert.AreEqual(ValueGenerator.GetPreviousValue<String>(), blahBlahBlahRequest.@J);
		}
		
		#endregion
	}
}
