//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by:
// TextMetal 4.4.5.2714;
// 		Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
//		Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
//		Project URL: https://github.com/dpbullington/textmetal
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

/*
	Copyright ©2002-2012 Daniel Bullington (dpbullington@gmail.com)
	Distributed under the MIT license: http://www.opensource.org/licenses/mit-license.php
*/

using System;
using System.Collections.Generic;

using NUnit.Framework;

using TestingFramework.Core.Customization;

using TextMetal.WebHostSample.Objects.Model.Procedures;

namespace TextMetal.WebHostSample.Objects.Model.UnitTests.Procedures
{
	[TestFixture]
	public sealed class BlahBlahBlah_ResponseTests
	{		
		#region Constructors/Destructors
		
		public BlahBlahBlah_ResponseTests()
		{
		}
		
		#endregion
			
		#region Methods/Operators
		
		[Test]
		public void ShouldCreateBlahBlahBlahTest()
		{			
			BlahBlahBlah_Response blahBlahBlahResponse;
			
			blahBlahBlahResponse = new BlahBlahBlah_Response();
			
			Assert.IsNotNull(blahBlahBlahResponse.Results);

			blahBlahBlahResponse.@J = ValueGenerator.GetNextValue<String>();
			Assert.AreEqual(ValueGenerator.GetPreviousValue<String>(), blahBlahBlahResponse.@J);

			blahBlahBlahResponse.@ReturnValue = ValueGenerator.GetNextValue<Int32>();
			Assert.AreEqual(ValueGenerator.GetPreviousValue<Int32>(), blahBlahBlahResponse.@ReturnValue);
		}
		
		#endregion
	}
}
